sudo: false
language: perl
perl:
    - 'blead'
    - '5.26'
    - '5.24'
    - '5.22'
matrix:
    allow_failures:
        - perl: 'blead'
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
    - cpanm --quiet --skip-satisfied HTML::Template
script:
    - cd site/
    - perl new_site_bin/update_site.pl --repo . --outdir ~/perl.org.il/www/
